plugins {
    id 'java'
    id 'org.springframework.boot' version '3.4.5'
    id 'io.spring.dependency-management' version '1.1.7'
    id "maven-publish"
    id 'signing'
}

def buildPropertiesFile = file("build.properties")
def buildProps = new Properties()

if (buildPropertiesFile.exists()) {
    buildProps.load(new FileInputStream(buildPropertiesFile))
}

def ossrhUsername = buildProps.getProperty("ossrhUsername", "")
def ossrhPassword = buildProps.getProperty("ossrhPassword", "")


group = 'io.github.benchpress200'
version = '0.0.1'

java {
    withSourcesJar()
    withJavadocJar()
}

jar {
    enabled = true
}

repositories {
    mavenCentral()
}

dependencies {
    implementation 'org.springframework.boot:spring-boot-starter-web:3.4.5'
}

publishing {
    publications {
        mavenJava(MavenPublication) {
            from components.java

            groupId = 'io.github.benchpress200'
            artifactId = 'api-response'
            version = '0.0.1'

            pom {
                name = 'ApiResponse'
                description = 'A simple Spring API response builder'
                url = 'https://github.com/BenchPress200/api-response'

                licenses {
                    license {
                        name = 'MIT License'
                        url = 'https://opensource.org/licenses/MIT'
                    }
                }

                developers {
                    developer {
                        id = 'benchpress200'
                        name = 'BenchPress200'
                        email = 'jms0538@naver.com'
                    }
                }

                scm {
                    connection = 'scm:git:git://github.com/BenchPress200/api-response.git'
                    developerConnection = 'scm:git:ssh://github.com:BenchPress200/api-response.git'
                    url = 'https://github.com/BenchPress200/api-response'
                }
            }
        }
    }

    repositories {
        maven {
            name = 'ossrh-staging-api'
            url = "https://ossrh-staging-api.central.sonatype.com/service/local/staging/deploy/maven2/"
            credentials {
                username = ossrhUsername
                password = ossrhPassword
            }
        }
    }
}

signing {
    useGpgCmd()
    sign publishing.publications.mavenJava
}